server:
  port: 8000
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sys?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: root
    password: Root@9104

  jpa:
    hibernate:
      ddl-auto: create-drop #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    properties:
      hibernate.transaction.jta.platform: org.hibernate.service.jta.JtaPlatform

#  devtools:
#    restart:
#      enabled: false
#logging.level.org.springframework: debug;